import type { Pet } from '../shared/types';
import type { Dispatch, FunctionComponent, SetStateAction } from 'react';
import type * as ReactNS from 'react';
import type { jsx } from 'react/jsx-runtime';
/** 容器与设置页共享的桥（同一 bundle 单例）：
 * current=最新完整宠物列表（**成品拍平**，含条目级字段与文件宠物，默认空；容器是唯一写入方）；
 * reload=容器注册的重载回调（未注册时为无操作函数）：传 host 保存接口返回的成品聚合即直接拍平，
 *   缺省则由容器自行 GET /config；template=main 条目的宠物[0]（「添加宠物」用它作为默认配置） */
export declare const petBridge: {
    current: Pet[];
    reload: (merged?: Record<string, Record<string, unknown>>) => void;
    template: Pet | undefined;
};
/** 字典命名空间 */
export declare const NS = "pet.config";
export declare const zh: {
    nav: string;
    intro: string;
    petCardTitle: string;
    petCardHint: string;
    globalTitle: string;
    globalHint: string;
    cornerHint: string;
    marginXHint: string;
    marginYHint: string;
    'cmd.chat': string;
    'cmd.pet': string;
    'cmd.balance': string;
    petsLabel: string;
    add: string;
    remove: string;
    confirmRemove: string;
    confirmTitle: string;
    cancel: string;
    ok: string;
    atLeastOne: string;
    emptyPets: string;
    sizeLabel: string;
    sizeHint: string;
    nameLabel: string;
    nameHint: string;
    balanceEnabled: string;
    balanceEnabledHint: string;
    whisperEnabled: string;
    whisperEnabledHint: string;
    workStatusEnabled: string;
    workStatusEnabledHint: string;
    fixedEnabled: string;
    fixedEnabledHint: string;
    displayLabel: string;
    displayHint: string;
    'display.web': string;
    'display.desktop': string;
    'display.both': string;
    'display.none': string;
    cornerLabel: string;
    'corner.top-left': string;
    'corner.top-right': string;
    'corner.bottom-left': string;
    'corner.bottom-right': string;
    marginX: string;
    marginY: string;
    save: string;
    sync: string;
    confirmSync: string;
    corruptTitle: string;
    corruptConfirm: string;
    corruptBody: string;
    syncHint: string;
    configMeta: string;
    configMetaHint: string;
    defaultConfig: string;
    userConfig: string;
    animationDir: string;
    memesDir: string;
    saved: string;
    loadError: string;
    invalid: string;
    busy: string;
    extraPetsHint: string;
    notifyToggle: string;
    notifyToggleHint: string;
    whisperImageToggle: string;
    whisperImageToggleHint: string;
    chatImageToggle: string;
    chatImageToggleHint: string;
    confineToggle: string;
    confineToggleHint: string;
    physicsTitle: string;
    physicsHint: string;
    'physics.gravity': string;
    'physics.gravityHint': string;
    'physics.restitution': string;
    'physics.restitutionHint': string;
    'physics.groundFriction': string;
    'physics.groundFrictionHint': string;
    'physics.throwPower': string;
    'physics.throwPowerHint': string;
    physicsCeilingBounce: string;
    physicsCeilingBounceHint: string;
    physicsPetCollision: string;
    physicsPetCollisionHint: string;
    invalidPhysics: string;
    modelTitle: string;
    modelHint: string;
    modelFollow: string;
    modelSearch: string;
    modelEmpty: string;
    modelNoModels: string;
    modelLoading: string;
    modelTriggerAria: string;
    modelUnknown: string;
    modelNone: string;
    whisperModelLabel: string;
    chatModelLabel: string;
    modelFieldHint: string;
    invalidModel: string;
    modelCatalogFailed: string;
    chatMemory: string;
    chatMemoryHint: string;
    invalidChatMemory: string;
    chatImageLimit: string;
    chatImageLimitHint: string;
    invalidChatImageLimit: string;
    notifyTest: string;
    notifyTestOk: string;
    notifyDenyUnsupported: string;
    notifyDenyBlocked: string;
    notifyDenyRejected: string;
    notifyDenyError: string;
    notifyGuide: string;
    storageTitle: string;
    storageHint: string;
    'storage.userData': string;
    'storage.electron': string;
    'storage.desktopCache': string;
    'storage.electronCache': string;
    'storage.package': string;
    storageMissing: string;
    uninstallTitle: string;
    uninstallStep1: string;
    uninstallStep2: string;
    uninstallStep3: string;
    uninstallCmd: string;
};
export declare const en: {
    nav: string;
    intro: string;
    petCardTitle: string;
    petCardHint: string;
    globalTitle: string;
    globalHint: string;
    cornerHint: string;
    marginXHint: string;
    marginYHint: string;
    'cmd.chat': string;
    'cmd.pet': string;
    'cmd.balance': string;
    petsLabel: string;
    add: string;
    remove: string;
    confirmRemove: string;
    confirmTitle: string;
    cancel: string;
    ok: string;
    atLeastOne: string;
    emptyPets: string;
    sizeLabel: string;
    sizeHint: string;
    nameLabel: string;
    nameHint: string;
    balanceEnabled: string;
    balanceEnabledHint: string;
    whisperEnabled: string;
    whisperEnabledHint: string;
    workStatusEnabled: string;
    workStatusEnabledHint: string;
    fixedEnabled: string;
    fixedEnabledHint: string;
    displayLabel: string;
    displayHint: string;
    'display.web': string;
    'display.desktop': string;
    'display.both': string;
    'display.none': string;
    cornerLabel: string;
    'corner.top-left': string;
    'corner.top-right': string;
    'corner.bottom-left': string;
    'corner.bottom-right': string;
    marginX: string;
    marginY: string;
    save: string;
    sync: string;
    confirmSync: string;
    corruptTitle: string;
    corruptConfirm: string;
    corruptBody: string;
    syncHint: string;
    configMeta: string;
    configMetaHint: string;
    defaultConfig: string;
    userConfig: string;
    animationDir: string;
    memesDir: string;
    saved: string;
    loadError: string;
    invalid: string;
    busy: string;
    extraPetsHint: string;
    notifyToggle: string;
    notifyToggleHint: string;
    whisperImageToggle: string;
    whisperImageToggleHint: string;
    chatImageToggle: string;
    chatImageToggleHint: string;
    confineToggle: string;
    confineToggleHint: string;
    physicsTitle: string;
    physicsHint: string;
    'physics.gravity': string;
    'physics.gravityHint': string;
    'physics.restitution': string;
    'physics.restitutionHint': string;
    'physics.groundFriction': string;
    'physics.groundFrictionHint': string;
    'physics.throwPower': string;
    'physics.throwPowerHint': string;
    physicsCeilingBounce: string;
    physicsCeilingBounceHint: string;
    physicsPetCollision: string;
    physicsPetCollisionHint: string;
    invalidPhysics: string;
    modelTitle: string;
    modelHint: string;
    modelFollow: string;
    modelSearch: string;
    modelEmpty: string;
    modelNoModels: string;
    modelLoading: string;
    modelTriggerAria: string;
    modelUnknown: string;
    modelNone: string;
    whisperModelLabel: string;
    chatModelLabel: string;
    modelFieldHint: string;
    invalidModel: string;
    modelCatalogFailed: string;
    chatMemory: string;
    chatMemoryHint: string;
    invalidChatMemory: string;
    chatImageLimit: string;
    chatImageLimitHint: string;
    invalidChatImageLimit: string;
    notifyTest: string;
    notifyTestOk: string;
    notifyDenyUnsupported: string;
    notifyDenyBlocked: string;
    notifyDenyRejected: string;
    notifyDenyError: string;
    notifyGuide: string;
    storageTitle: string;
    storageHint: string;
    'storage.userData': string;
    'storage.electron': string;
    'storage.desktopCache': string;
    'storage.electronCache': string;
    'storage.package': string;
    storageMissing: string;
    uninstallTitle: string;
    uninstallStep1: string;
    uninstallStep2: string;
    uninstallStep3: string;
    uninstallCmd: string;
};
/**
 * 制造「桌宠配置」设置页组件（工厂函数）。
 *
 * 为什么是工厂而非直接定义组件：client 半侧是 __ModuleLoader__ 单文件形态，
 * react 能力不能顶层 import，只能由 DSH 的 require('react') 在运行时注入，
 * 因此把组件依赖作为参数传入，在工厂内制造出可用的组件后再注册进设置页插槽。
 *
 * @param rt        运行时注入的依赖集合
 * @param rt.h      react/jsx-runtime 的 jsx 函数（即 factory 里的 `h`）——
 *                  用于手写 React 元素，如 `h('button', { onClick, children: '保存' })`
 * @param rt.useState react 的 useState hook——管理页面内可变状态
 *                  （宠物列表 / 选中项 / 忙碌 / 保存消息），值变化时自动重渲染
 * @param rt.useRef react 的 useRef hook——「AI 模型」单下拉选择器用它拿触发器/浮层节点
 *                  （浮层定位与"点外面关闭"判定），与宠物页面同一份注入
 * @param rt.t      locale 绑定到本插件的翻译函数（ctx.locale.bind(NS)）——
 *                  取中英文文案，如 `t('nav')` → '桌宠配置' / 'Pet Config'
 * @returns PetConfigSection 组件：即整个「桌宠配置」设置页
 *          （props 仅有 close，由设置页外壳提供，本页当前未使用）
 */
export declare function makePetConfigSection(rt: {
    h: typeof jsx;
    useState: <T>(init: T) => [T, Dispatch<SetStateAction<T>>];
    useEffect: (effect: ReactNS.EffectCallback, deps?: ReactNS.DependencyList) => void;
    useRef: <T>(initial: T) => ReactNS.MutableRefObject<T>;
    t: (key: string) => string;
}): FunctionComponent<{
    close?: () => void;
}>;
